# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0004_auto_20191101_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Profile'),
            preserve_default=False,
        ),
    ]
